### ISSUE TITLE
Does not install m2560def.inc

### ISSUE THREAD

**Issue by Cypher1** [timofurrer/avra-atmega2560#1]
Initial installation doesn't include m2560def.inc which is needed in many/most files.

**Comment by timofurrer** [comment]
I didn't get what you need.
The file m2560def.inc is here: https://github.com/timofurrer/avra-atmega2560/blob/master/avra-1.3.0/includes/m2560def.inc

**Comment by Cypher1** [comment]
In that case, how does one allow it to be included when compiling. On my
machine I could not compile and have the includes automatically included
but had to do so by hand.

**Comment by timofurrer** [comment]
There are two ways:
Either you copy this file to your project folder and include it relative or you specify the path to the m2560def.inc in your installation folder.

**Comment by Cypher1** [comment]
Okay. I'll try that
